### ISSUE TITLE
Binary link is dead. Here's a mirror link.

### ISSUE THREAD

**Issue by honguyenminh** [kuna/bmx2ogg#2]
Mirror Google Drive link for temporary use: https://drive.google.com/drive/folders/1rnzxWLQat2TwMJrOOp7I1rLCaZoJFDSG?usp=sharing

Kuna pls upload binary again to GitHub release tab, link wont die that way.

**Comment by kuna** [comment]
Hello, thank you so much for your mirror!
I upload v0.1 release thanks to you: https://github.com/kuna/bmx2ogg/releases/tag/v0.1
And sorry for late reply. I had not much time recently, also for maintaining my side projects.
