### ISSUE TITLE
Generated WAVs are messed up (with CompleteMIX2's files)

### ISSUE THREAD

**Issue by Sakimotor** [kuna/bmx2ogg#3]
Hello there !

Yesterday I decided to gamerip beatmania CompleteMIX2 thanks to the [DJMainExtract](https://github.com/SaxxonPike/scharfrichter) tool. It extracted the game's files as required, so I simply parsed them through your tool. 

Unfortunately, the results seem to be broken, with the notes playing at inappropriate places.

Here is the log for the conversion process :

```cmd
C:\Users\saki\Jeux\Emulateurs\MAME\roms\bmcompm2\completemix2>bmx2ogg-flac.exe "005\@005 [another].bms" -ob -wav -q 1 -
autofn
BMS Path: 005\@005 [another].bms
BMS Title: 005
BMS Artist: (none)
BMS Length: 44.201 (sec)
Output Path: 005/[(none)] 005.wav
Loading Audio Data ...
[Warning] Cannot find wav/ogg file(005\0002.wav). ignore.
Start Mixing ...
Cut / Normalize ...
Writing file ...
Finished!
```

Here is a sample of the file I converted : [Link](https://drive.google.com/file/d/129mPUGfBEGU5rGkWTfTpJ4mUsHPVwogn/view?usp=sharing)

Do you know how to fix this issue ? Thanks in advance !

**Comment by kuna** [comment]
Hi @Sakimotor , though this project is depreciated one, I have interest in various BMS format and so I looked into it.
Though there is no tag in bms file, I think your song data is [CHAIN -CONNECTION MIX-](https://www.youtube.com/watch?v=Si1AG_9hmsc).
Actually I found nothing special in your result nor mine, compared to original song.
Could you tell me of which music part makes you think as broken?

**Comment by Sakimotor** [comment]
> Hi @Sakimotor , though this project is depreciated one, I have interest in various BMS format and so I looked into it. Though there is no tag in bms file, I think your song data is [CHAIN -CONNECTION MIX-](https://www.youtube.com/watch?v=Si1AG_9hmsc). Actually I found nothing special in your result nor mine, compared to original song. Could you tell me of which music part makes you think as broken?


The song is indeed CHAIN ~CONNECTION MIX~, a CompleteMIX2 exclusive that has never been released on an official soundtrack. You can clearly hear at 45 seconds the keysounds that are supposed to play at the end of the song, which also explains why the remaining 30 seconds of the generated wav feel "empty"

**Comment by kuna** [comment]
Okay, from some time point (as you mentioned) the keysound seems not playing anymore. I'll check about it.

**Comment by kuna** [comment]
The reason of problem is due to comma(decimal value) in measure length. this depreciated bmsbelplus parser only support integer value on measure length. (rparser supports it)
You can detour this problem by making all decimal as integer in `#02` channel, or just replace zero to one like attached image. This will make output more natural. (but not exact result, maybe)
<img width="794" alt="Screen Shot 2022-03-26 at 12 01 37 AM" src="https://user-images.githubusercontent.com/1835950/160146980-698bbc00-8de5-4b4c-a687-ccdd071134e8.png">

**Comment by Sakimotor** [comment]
> The reason of problem is due to comma(decimal value) in measure length. this depreciated bmsbelplus parser only support integer value on measure length. (rparser supports it) You can detour this problem by making all decimal as integer in `#02` channel, or just replace zero to one like attached image. This will make output more natural. (but not exact result, maybe) <img alt="Screen Shot 2022-03-26 at 12 01 37 AM" width="794" src="https://user-images.githubusercontent.com/1835950/160146980-698bbc00-8de5-4b4c-a687-ccdd071134e8.png">

Yeah, replacing the decimals by integers fixed all the issues. Thank you !
